<?php
$products = [
    [
        'id' => 1,
        'category' => 'clothing',
        'name' => "Garson Down-Filled Vest",
        'image' => "assets/images/clothing/20138721075.png",
        'price' => number_format('650', 2, '.', ''),
    ],
    [
        'id' => 2,
        'category' => 'accessories',
        'name' => "Alpha Bravo Navigation Backpack",
        'image' => "assets/images/accessories/20089559075.png",
        'price' => number_format('435', 2, '.', ''),
    ],
    [
        'id' => 3,
        'category' => 'footwear',
        'name' => "THE ROGER Center Court 2 Sneakers",
        'image' => "assets/images/footwear/20134166070.png",
        'price' => number_format('250', 2, '.', ''),
    ],
    [
        'id' => 4,
        'category' => 'grooming',
        'name' => "Aventus Eau de Parfum 100ml",
        'image' => "assets/images/grooming/20011872.png",
        'price' => number_format('629', 2, '.', ''),
    ],
    [
        'id' => 5,
        'category' => 'clothing',
        'name' => "Virgin Wool Serge Suit Jacket",
        'image' => "assets/images/clothing/20093788105.png",
        'price' => number_format('899', 2, '.', ''),
    ],
    [
        'id' => 6,
        'category' => 'accessories',
        'name' => "Eagle Leather Detailed Backpack",
        'image' => "assets/images/accessories/20150202301.png",
        'price' => number_format('450', 2, '.', ''),
    ],
    [
        'id' => 7,
        'category' => 'footwear',
        'name' => "Grain Leather Byron Sneaker",
        'image' => "assets/images/footwear/20134006067.png",
        'price' => number_format('595', 2, '.', ''),
    ],
    [
        'id' => 8,
        'category' => 'grooming',
        'name' => "Liquors Discovery 5-Piece Set",
        'image' => "assets/images/grooming/20161692999.png",
        'price' => number_format('575', 2, '.', ''),
    ],
    [
        'id' => 9,
        'category' => 'clothing',
        'name' => "Slim Fit Jersey Cotton T-Shirt",
        'image' => "assets/images/clothing/20072880070.png",
        'price' => number_format('270', 2, '.', ''),
    ],
    [
        'id' => 10,
        'category' => 'accessories',
        'name' => "Fletcher Vintage-Style Square Frame Sunglasses",
        'image' => "assets/images/accessories/20071577067.png",
        'price' => number_format('655', 2, '.', ''),
    ],
    [
        'id' => 11,
        'category' => 'footwear',
        'name' => "Deerskin Shearling Lined Cap-Toe Zip Boot",
        'image' => "assets/images/footwear/20096486075.png",
        'price' => number_format('995', 2, '.', ''),
    ],
    [
        'id' => 12,
        'category' => 'grooming',
        'name' => "Tuscan Leather Eau De Parfum 50ml",
        'image' => "assets/images/grooming/56730006.png",
        'price' => number_format('390', 2, '.', ''),
    ],
    [
        'id' => 13,
        'category' => 'clothing',
        'name' => "Micro Modal Hooded Sweater",
        'image' => "assets/images/clothing/20084009074.png",
        'price' => number_format('899', 2, '.', ''),
    ],
    [
        'id' => 14,
        'category' => 'accessories',
        'name' => "Reversible Leather Belt",
        'image' => "assets/images/accessories/20093239075.png",
        'price' => number_format('615', 2, '.', ''),
    ],
    [
        'id' => 15,
        'category' => 'footwear',
        'name' => "Leather & Suede Welt Penny Loafers",
        'image' => "assets/images/footwear/20155017070.png",
        'price' => number_format('1190', 2, '.', ''),
    ],
    [
        'id' => 16,
        'category' => 'grooming',
        'name' => "Ombre Leather Eau de Parfum 100ml",
        'image' => "assets/images/grooming/20031411.png",
        'price' => number_format('315', 2, '.', ''),
    ],
    [
        'id' => 17,
        'category' => 'clothing',
        'name' => "Linen Shirt",
        'image' => "assets/images/clothing/20131578055.png",
        'price' => number_format('899', 2, '.', ''),
    ],
    [
        'id' => 18,
        'category' => 'accessories',
        'name' => "Vegetable-Tanned Leather Miniwallet",
        'image' => "assets/images/accessories/20059878.png",
        'price' => number_format('130', 2, '.', ''),
    ],
    [
        'id' => 19,
        'category' => 'footwear',
        'name' => "PGrain Leather Byron Sneakers",
        'image' => "assets/images/footwear/20134008075.png",
        'price' => number_format('595', 2, '.', ''),
    ],
    [
        'id' => 20,
        'category' => 'grooming',
        'name' => "No.89 Moisturizing Bath & Shower Gel 250ml",
        'image' => "assets/images/grooming/20105616999.png",
        'price' => number_format('68', 2, '.', ''),
    ],
    [
        'id' => 21,
        'category' => 'clothing',
        'name' => "Bozen Ultralight Bermuda Shorts",
        'image' => "assets/images/clothing/20156106046.png",
        'price' => number_format('899', 2, '.', ''),
    ],
    [
        'id' => 22,
        'category' => 'accessories',
        'name' => "Zair Envelope Bag",
        'image' => "assets/images/accessories/20146179075.png",
        'price' => number_format('130.99', 2, '.', ''),
    ],
    [
        'id' => 23,
        'category' => 'footwear',
        'name' => "Softey Suede Yacht Loafers",
        'image' => "assets/images/footwear/20164864047.png",
        'price' => number_format('535', 2, '.', ''),
    ],
    [
        'id' => 24,
        'category' => 'grooming',
        'name' => "Aventus Cologne 100ml",
        'image' => "assets/images/grooming/20050461.png",
        'price' => number_format('629', 2, '.', ''),
    ],
    [
        'id' => 25,
        'category' => 'clothing',
        'name' => "Hooded Gingham Wool Overshirt",
        'image' => "assets/images/clothing/20093788105.png",
        'price' => number_format('1695', 2, '.', ''),
    ],
    [
        'id' => 26,
        'category' => 'accessories',
        'name' => "Wool-Angora Classic Toque",
        'image' => "assets/images/accessories/20097658074.png",
        'price' => number_format('575', 2, '.', ''),
    ],
    [
        'id' => 27,
        'category' => 'footwear',
        'name' => "Amedeo Derby Lace-Up",
        'image' => "assets/images/footwear/20088295075.png",
        'price' => number_format('345.99', 2, '.', ''),
    ],
    [
        'id' => 28,
        'category' => 'grooming',
        'name' => "Tabacco Vanille Conditioning Beard Oil",
        'image' => "assets/images/grooming/56730164.png",
        'price' => number_format('85', 2, '.', ''),
    ],
    [
        'id' => 29,
        'category' => 'clothing',
        'name' => "Basile Textured Overshirt",
        'image' => "assets/images/clothing/20166803061.png",
        'price' => number_format('495', 2, '.', ''),
    ],
    [
        'id' => 30,
        'category' => 'accessories',
        'name' => "John Touchscreen-Compatible Hairsheep Gloves",
        'image' => "assets/images/accessories/20097145067.png",
        'price' => number_format('210', 2, '.', ''),
    ],
    [
        'id' => 31,
        'category' => 'footwear',
        'name' => "Suede Loafers",
        'image' => "assets/images/footwear/20168383047.png",
        'price' => number_format('1010', 2, '.', ''),
    ],
    [
        'id' => 32,
        'category' => 'grooming',
        'name' => "Ebene Fume Eau De Parfum 10ml",
        'image' => "assets/images/grooming/20102027999.png",
        'price' => number_format('95', 2, '.', ''),
    ],
];
?>
