<?php
$products = [
    [
        'id' => 1,
        'category' => 'clothing',
        'name' => "CHANEL Matelasse 30 Double Chain Flap Shoulder Bag Lambskin, Black A58600",
        'image' => "assets/images/CHANEL_Matelasse_30_Double_Chain_Flap_Shoulder_Bag_Lambskin.jpg",
        'price' => number_format('1.56', 2, '.', ''),
    ],
    [
        'id' => 2,
        'category' => 'jewelry',
        'name' => "Gucci Blondie large top handle bag",
        'image' => "assets/images/Gucci_Blondie_large_top_handle_bag.jpg",
        'price' => number_format('4390.00', 2, '.', ''),
    ],
    [
        'id' => 3,
        'category' => 'clothing',
        'name' => "Mon Monogram OnTheGo MM Bag",
        'image' => "assets/images/louis-vuitton-mon-monogram-onthego-mm-bag--P01898_PM2.jpg",
        'price' => number_format('3353.23', 2, '.', ''),
    ],
    [
        'id' => 4,
        'category' => 'clothing',
        'name' => "CHANEL 25 Medium Backpack",
        'image' => "assets/images/9569686487070.jpg",
        'price' => number_format('6841.51', 2, '.', ''),
    ],
    [
        'id' => 5,
        'category' => 'clothing',
        'name' => "Gucci Totissima large reversible tote bag",
        'image' => "assets/images/839112_AAFEQ_6258_001_100_0000_Light.jpg",
        'price' => number_format('2800', 2, '.', ''),
    ],
    [
        'id' => 6,
        'category' => 'clothing',
        'name' => "Nano Boulogne Bag",
        'image' => "assets/images/louis-vuitton-nano-boulogne-bag--M25519_PM2.jpg",
        'price' => number_format('1904.76', 2, '.', ''),
    ],
    [
        'id' => 7,
        'category' => 'clothing',
        'name' => "Rodeo handbag medium grained calfskin",
        'image' => "assets/images/Small-7897722ABV52914_X.jpg",
        'price' => number_format('4450', 2, '.', ''),
    ],
    [
        'id' => 8,
        'category' => 'clothing',
        'name' => "Woven medium tote bag",
        'image' => "assets/images/834971_FAETR_8550_001_100_0000_Light.jpg",
        'price' => number_format('2550', 2, '.', ''),
    ],
    [
        'id' => 9,
        'category' => 'clothing',
        'name' => "Ophidia medium boston bag",
        'image' => "assets/images/836825_FAE0J_9867_001_086_0000_Light.jpg",
        'price' => number_format('1950', 2, '.', ''),
    ],
    [
        'id' => 10,
        'category' => 'clothing',
        'name' => "Flap Bag Shiny Lambskin & Gold",
        'image' => "assets/images/9572455612446.jpg",
        'price' => number_format('5090.85', 2, '.', ''),
    ],
    [
        'id' => 11,
        'category' => 'clothing',
        'name' => "Dior Saddle Bag",
        'image' => "assets/images/louis-vuitton-mon-monogram-alma-bb-bag--P01917_PM2.jpg",
        'price' => number_format('2146.21', 2, '.', ''),
    ],
    [
        'id' => 12,
        'category' => 'clothing',
        'name' => "CLASSIC 11.12 HANDBAG",
        'image' => "assets/images/9572446273566.jpg",
        'price' => number_format('8029.58', 2, '.', ''),
    ],
    [
        'id' => 13,
        'category' => 'clothing',
        'name' => "Neverfull Inside Out MM Bag",
        'image' => "assets/images/louis-vuitton-neverfull-mm-bag--M14285_PM2.jpg",
        'price' => number_format('3058.35', 2, '.', ''),
    ],
    [
        'id' => 14,
        'category' => 'clothing',
        'name' => "Bel air carry all bag medium",
        'image' => "assets/images/Large-8356702ABAW3503_X.jpg",
        'price' => number_format('5300', 2, '.', ''),
    ],
    [
        'id' => 15,
        'category' => 'clothing',
        'name' => "Gucci Softbit maxi shoulder bag",
        'image' => "assets/images/837466_AAEAO_2718_001_093_0000_Light.jpg",
        'price' => number_format('3650', 2, '.', ''),
    ],
];
?>
